#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
START=66

USE_PROCD=1


start_service() {
	procd_open_instance
    # -s: log to syslog
    # -f: run in foreground
    procd_set_param command /bin/pppoe_plus -f /etc/pppoe_plus/pppoe_plus.conf >/dev/null 2>&1
    #procd_set_param respawn # respawn automatically if something died
    procd_set_param file /etc/pppoe_plus/pppoe_plus.conf
    procd_close_instance
}


stop_service() {
	killall -9 pppoe_plus
}